version: '3.1'

services:
  certbot:
    build:
      context: .
      dockerfile: certbot.Dockerfile
      args:
        EMAIL: $EMAIL
        DOMAIN: $DOMAIN
    volumes:
      - hosting_ssl:/ssl
      - hosting_letsencrypt:/etc/letsencrypt
    command: ["/run_once"]

volumes:
  hosting_ssl:
    external: true
  hosting_letsencrypt:
    external: true
