version: "3.1"

services:
  facades_db:
    container_name: facades_db
    image: postgis/postgis:14-3.3
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file: db.env
    restart: until-stopped

  facades_classificator:
    container_name: facades_classifier
    build:
      context: classifier
    ports:
      - ${CLASSIFIER_EXPOSE_PORT}:8081
    env_file: ./classifier/.env
    restart: until-stopped

  facades_backend:
    container_name: facades_backend
    build: ./backend
    env_file: ./backend/.env
    env:
      - PHOTOS_DIRECTORY=/photos
    volumes:
      - ./photos:/photos
    depends_on:
      - facades_db
      - facades_classifier
    restart: until-stopped

  facades_nginx:
    container_name: facades_nginx
    build:
      context: hosting
      dockerfile: nginx.Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        BACKEND_ADDRESS: ${BACKEND_ADDRESS}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    env_file:
      .env
    volumes:
      - ./hosting/config/ssl:/ssl
    depends_on:
      - facades_backend
    restart: until-stopped

  facades_certificate_updater:
    container_name: facades_certificate_updater
    build:
      context: hosting
      dockerfile: certbot.Dockerfile
      args:
        EMAIL: ${EMAIL}
        DOMAIN: ${DOMAIN}
    volumes:
      - ./hosting/config/ssl:/ssl
      - ./hosting/config/letsencryptl:/etc/letsencrypt
    depends_on:
      - facades_nginx
