version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx-http-only.Dockerfile
      args:
        BACKEND_ADDRESS: ${BACKEND_ADDRESS}
    ports:
      - ${HTTP_PORT}:80
    env_file:
      .env
    volumes:
      - ./config/ssl:/ssl
