version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        BACKEND_ADDRESS: ${BACKEND_ADDRESS}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    env_file:
      .env
    volumes:
      - ./config/ssl:/ssl
